"""CDK L2 renderer — generates an AWS CDK Python project from an InfraBlueprint.

Produces:
  cdk/app.py           — CDK app entry point
  cdk/cdk.json         — CDK config
  cdk/requirements.txt — pip deps
  cdk/stacks/<brick>_stack.py — one stack per brick
  cdk/stacks/network_stack.py — if VPC required
"""

from __future__ import annotations

from typing import Any

from ...core import SERVICE_CDK_MODULES, VPC_REQUIRED_SERVICES
from ..ports import InfraBlueprint, NormalizedResource, RenderedOutput


class CdkRenderer:
    """Renders CDK L2 Python project files from an InfraBlueprint."""

    @property
    def renderer_type(self) -> str:
        return "cdk"

    def validate(self, blueprint: InfraBlueprint) -> list[str]:
        """Check for unsupported services."""
        errors: list[str] = []
        for res in blueprint.resources:
            if res.service not in SERVICE_CDK_MODULES:
                errors.append(f"Unsupported service: {res.service}")
        return errors

    def render(self, blueprint: InfraBlueprint, project_name: str) -> RenderedOutput:
        """Generate CDK project files."""
        files: dict[str, str] = {}
        bricks = _group_by_brick(blueprint.resources)

        # Per-brick stacks
        stack_names: list[str] = []
        for brick, resources in sorted(bricks.items()):
            stack_name = f"{brick}_stack"
            stack_names.append(stack_name)
            files[f"cdk/stacks/{stack_name}.py"] = _render_stack(
                brick, resources, project_name,
            )

        # Network stack if VPC required
        if blueprint.vpc_required:
            stack_names.insert(0, "network_stack")
            files["cdk/stacks/network_stack.py"] = _render_network_stack(
                project_name,
            )

        files["cdk/stacks/__init__.py"] = ""
        files["cdk/app.py"] = _render_app(project_name, stack_names)
        files["cdk/cdk.json"] = _render_cdk_json()
        files["cdk/requirements.txt"] = _render_requirements(blueprint)

        modules_used = sorted(blueprint.services_used)
        return RenderedOutput(
            files=files, entry_point="cdk/app.py",
            metadata={"stacks": stack_names, "services": modules_used},
        )


# ── Private helpers ────────────────────────────────────────────────


def _group_by_brick(
    resources: list[NormalizedResource],
) -> dict[str, list[NormalizedResource]]:
    groups: dict[str, list[NormalizedResource]] = {}
    for res in resources:
        groups.setdefault(res.brick, []).append(res)
    return groups


def _render_app(project_name: str, stack_names: list[str]) -> str:
    imports = "\n".join(
        f"from stacks.{s} import {_class_name(s)}" for s in stack_names
    )
    stacks = "\n".join(
        f'{_class_name(s)}(app, "{project_name}-{s.replace("_", "-")}")'
        for s in stack_names
    )
    return f"""\
#!/usr/bin/env python3
\"\"\"CDK app entry point — auto-generated by blueprint.\"\"\"
import aws_cdk as cdk
{imports}

app = cdk.App()
{stacks}
app.synth()
"""


def _render_cdk_json() -> str:
    return '{\n  "app": "python3 app.py",\n  "context": {}\n}\n'


def _render_requirements(blueprint: InfraBlueprint) -> str:
    modules: set[str] = {"aws-cdk-lib", "constructs"}
    for res in blueprint.resources:
        entry = SERVICE_CDK_MODULES.get(res.service)
        if entry:
            pkg = entry[0].replace(".", "-").replace("aws_cdk-", "")
            modules.add("aws-cdk-lib")  # L2 constructs are in aws-cdk-lib
    return "\n".join(sorted(modules)) + "\n"


def _render_stack(
    brick: str, resources: list[NormalizedResource], project_name: str,
) -> str:
    imports: set[str] = set()
    constructs: list[str] = []

    for res in resources:
        entry = SERVICE_CDK_MODULES.get(res.service)
        if not entry:
            continue
        module, _, alias = entry
        imports.add(f"from {module} import {alias}")
        constructs.append(_render_construct(res, alias))

    import_lines = "\n".join(sorted(imports))
    construct_lines = "\n".join(constructs)
    class_name = _class_name(f"{brick}_stack")

    return f"""\
\"\"\"CDK stack for {brick} — auto-generated by blueprint.\"\"\"
from constructs import Construct
import aws_cdk as cdk
{import_lines}


class {class_name}(cdk.Stack):
    def __init__(self, scope: Construct, construct_id: str, **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)
{construct_lines}
"""


def _render_construct(res: NormalizedResource, alias: str) -> str:
    """Render a single CDK L2 construct instantiation."""
    var_name = res.logical_id[0].lower() + res.logical_id[1:]
    props_str = _format_props(res.props, indent=12)
    return f"""
        self.{var_name} = {alias}.{res.construct}(
            self, "{res.logical_id}",
{props_str}
        )"""


def _render_network_stack(project_name: str) -> str:
    return f"""\
\"\"\"Network stack (VPC) — auto-generated by blueprint.\"\"\"
from constructs import Construct
import aws_cdk as cdk
from aws_cdk import aws_ec2 as ec2


class NetworkStack(cdk.Stack):
    def __init__(self, scope: Construct, construct_id: str, **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)

        self.vpc = ec2.Vpc(
            self, "{project_name}-vpc",
            max_azs=2,
            nat_gateways=1,
        )
"""


def _format_props(props: dict[str, Any], indent: int = 12) -> str:
    """Format props dict as keyword arguments."""
    if not props:
        return ""
    pad = " " * indent
    lines: list[str] = []
    for key, value in props.items():
        lines.append(f"{pad}{key}={_format_value(value)},")
    return "\n".join(lines)


def _format_value(value: Any) -> str:
    if isinstance(value, str):
        return f'"{value}"'
    if isinstance(value, bool):
        return str(value)
    if isinstance(value, dict):
        inner = ", ".join(f'"{k}": {_format_value(v)}' for k, v in value.items())
        return "{" + inner + "}"
    return repr(value)


def _class_name(stack_name: str) -> str:
    """Convert snake_case to PascalCase."""
    return "".join(part.capitalize() for part in stack_name.split("_"))
