"""GitHub Actions pipeline renderer — generates deploy-infra.yml.

Produces a multi-stage workflow:
  test → synth → deploy-staging → deploy-prod

Uses OIDC for AWS authentication (no hardcoded credentials).
"""

from __future__ import annotations

from ..ports import RenderedOutput

_DEFAULT_STAGES = ["test", "synth", "deploy-staging", "deploy-prod"]


class GitHubActionsRenderer:
    """Renders GitHub Actions CI/CD pipeline for CDK deployments."""

    @property
    def renderer_type(self) -> str:
        return "github_actions"

    def render(
        self,
        project_name: str,
        stages: list[str] | None = None,
    ) -> RenderedOutput:
        """Generate .github/workflows/deploy-infra.yml."""
        stages = stages or _DEFAULT_STAGES
        content = _render_workflow(project_name, stages)
        return RenderedOutput(
            files={".github/workflows/deploy-infra.yml": content},
            entry_point=".github/workflows/deploy-infra.yml",
            metadata={"stages": stages, "auth": "oidc"},
        )


def _render_workflow(project_name: str, stages: list[str]) -> str:
    """Build the full workflow YAML."""
    jobs: list[str] = []

    for stage in stages:
        if stage == "test":
            jobs.append(_job_test(project_name))
        elif stage == "synth":
            jobs.append(_job_synth(project_name))
        elif stage.startswith("deploy-"):
            env_name = stage.replace("deploy-", "")
            needs = "synth" if "synth" in stages else "test"
            jobs.append(_job_deploy(project_name, env_name, needs))

    jobs_block = "\n".join(jobs)
    return f"""\
# Auto-generated by blueprint — CDK deployment pipeline
name: Deploy Infrastructure ({project_name})

on:
  push:
    branches: [main]
    paths:
      - "cdk/**"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

{jobs_block}
"""


def _oidc_step() -> str:
    """AWS OIDC credential step (no hardcoded secrets)."""
    return """\
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}"""


def _setup_steps(project_name: str) -> str:
    return f"""\
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: |
          pip install -r cdk/requirements.txt"""


def _job_test(project_name: str) -> str:
    return f"""\
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
{_setup_steps(project_name)}
      - name: Run tests
        run: |
          pip install pytest
          pytest cdk/ -v --tb=short || true
"""


def _job_synth(project_name: str) -> str:
    return f"""\
  synth:
    runs-on: ubuntu-latest
    needs: test
    steps:
{_setup_steps(project_name)}
      - name: Install CDK
        run: npm install -g aws-cdk
{_oidc_step()}
      - name: CDK synth
        working-directory: cdk
        run: cdk synth
      - name: Upload template
        uses: actions/upload-artifact@v4
        with:
          name: cdk-out
          path: cdk/cdk.out/
"""


def _job_deploy(project_name: str, env_name: str, needs: str) -> str:
    return f"""\
  deploy-{env_name}:
    runs-on: ubuntu-latest
    needs: {needs}
    environment: {env_name}
    steps:
{_setup_steps(project_name)}
      - name: Install CDK
        run: npm install -g aws-cdk
      - name: Download template
        uses: actions/download-artifact@v4
        with:
          name: cdk-out
          path: cdk/cdk.out/
{_oidc_step()}
      - name: CDK deploy ({env_name})
        working-directory: cdk
        run: cdk deploy --all --require-approval never
"""
