"""Lessons persistence port."""
from __future__ import annotations

from typing import Protocol

from .models import LessonRecord, LessonStatus


class LessonStore(Protocol):
    def create(self, record: LessonRecord) -> LessonRecord: ...
    def get(self, tenant_id: str, owner_id: str,
            lesson_id: str) -> LessonRecord | None: ...
    def get_by_identity(self, tenant_id: str, owner_id: str,
                        identity_key: str) -> LessonRecord | None: ...
    def list(self, tenant_id: str, owner_id: str,
             limit: int = 100) -> list[LessonRecord]: ...
    def enrich(self, record: LessonRecord, negative: str | None,
               evidence: tuple[str, ...],
               expected_revision: int) -> LessonRecord | None: ...
    def set_status(self, record: LessonRecord, status: LessonStatus,
                   expected_revision: int) -> LessonRecord | None: ...
    def remove(self, tenant_id: str, owner_id: str, lesson_id: str,
               expected_revision: int) -> bool: ...
    def list_unprojected(self, limit: int = 100) -> list[LessonRecord]: ...
    def mark_projected(self, record: LessonRecord, memory_id: str,
                       expected_revision: int) -> LessonRecord | None: ...
    def promote_explicit(self, record: LessonRecord, negative: str | None,
                         evidence: tuple[str, ...],
                         expected_revision: int) -> LessonRecord | None: ...


__all__ = ["LessonStore"]
