"""Byte-stable Economy & Ledger view payload declaration."""
from __future__ import annotations
from typing import Any


def economy_views() -> list[dict[str, Any]]:
    return [{"id": "blockchain-economy", "name": "Economy & Ledger", "brick": "blockchain", "icon": "⛓️", "layout": {"type": "flex", "direction": "column"}, "components": [_tx_mix_chart(), _transactions_list(), _activity_stream(), _graph_context_stream(), _bounties_list()], "metadata": {"description": "Transactions, bounties, and wallet-backed reward flow", "nav_label": "Blockchain", "nav_order": 65}}]


def _transactions_list() -> dict[str, Any]:
    return {"id": "bc-transactions", "type": "item_list", "props": {"data_tool": "blockchain_get_dashboard_summary", "data_path": "$.transactions", "item_key": "tx_id", "empty_icon": "banknotes", "empty_message": "No transactions yet.", "header": {"icon": "banknotes", "stats_tool": "blockchain_get_dashboard_summary", "stats_map": {"blocks": "$.overview.height", "wallets": "$.overview.wallets", "tx": "$.overview.transactions"}}, "filters": {"field": "tx_type", "values": ["transfer", "mint", "bounty_escrow", "bounty_release"], "colors": {"transfer": "blue", "mint": "emerald", "bounty_escrow": "yellow", "bounty_release": "purple"}, "show_counts": False}, "item_layout": {"status_dot": {"value_path": "$.status", "states": {"committed": "emerald", "pending": "yellow", "failed": "red"}}, "title": "$.tx_id", "subtitle": "$.status", "badge": {"field": "tx_type", "color_map": "filters.colors", "suffix": ""}, "value": {"path": "$.amount", "format": "number", "suffix": " tokens"}}, "detail": {"metadata": [{"label": "TX", "path": "$.tx_id", "render_as": "copy_id", "zone": "identity"}, {"label": "Type", "path": "$.tx_type", "render_as": "pills", "zone": "identity"}, {"label": "Status", "path": "$.status", "zone": "identity"}, {"label": "From", "path": "$.from_wallet", "render_as": "copy_id", "zone": "config"}, {"label": "To", "path": "$.to_wallet", "render_as": "copy_id", "zone": "config"}, {"label": "Amount", "path": "$.amount", "zone": "config"}, {"label": "Activity", "path": "$.activity_count", "zone": "identity"}, {"label": "Last Activity", "path": "$.last_activity_label", "zone": "config"}, {"label": "Memo", "path": "$.memo", "render_as": "popover", "zone": "config"}, {"label": "Block", "path": "$.block_height", "zone": "identity"}, {"label": "Timestamp", "path": "$.created_at", "render_as": "relative_time", "zone": "identity"}], "tabs": [{"id": "block", "label": "Block", "tool": "blockchain_get_block", "args": {"height": "$.block_height"}, "render_as": "json"}, {"id": "sender", "label": "From Wallet", "tool": "blockchain_get_wallet", "args": {"wallet_id": "$.from_wallet"}, "render_as": "json"}, {"id": "receiver", "label": "To Wallet", "tool": "blockchain_get_wallet", "args": {"wallet_id": "$.to_wallet"}, "render_as": "json"}, {"id": "activity", "label": "Activity", "tool": "blockchain_get_activity", "args": {"tx_id": "$.tx_id", "limit": 12}, "data_path": "$.entries", "render_as": "list", "empty_message": "No recorded activity for this transaction yet."}, {"id": "graph", "label": "Graph", "tool": "blockchain_get_entity_graph_context", "args": {"entity_id": "$.tx_id", "limit": 12}, "data_path": "$.entries", "render_as": "list", "empty_message": "No related graph entities found for this transaction yet."}]}}}


def _bounties_list() -> dict[str, Any]:
    return {"id": "bc-bounties", "type": "item_list", "props": {"data_tool": "blockchain_get_dashboard_summary", "data_path": "$.bounties", "item_key": "bounty_id", "empty_icon": "trophy", "empty_message": "No bounties posted yet.", "header": {"icon": "trophy", "stats_tool": "blockchain_get_dashboard_summary", "stats_map": {"bounties": "$.overview.bounties", "activity": "$.overview.activity"}}, "filters": {"field": "status", "values": ["open", "claimed", "cancelled", "expired"], "colors": {"open": "emerald", "claimed": "blue", "cancelled": "red", "expired": "gray"}, "show_counts": False}, "item_layout": {"status_dot": {"value_path": "$.status", "states": {"open": "emerald", "claimed": "blue", "cancelled": "red", "expired": "gray"}}, "title": "$.description", "subtitle": "$.poster_wallet", "badge": {"field": "status", "color_map": "filters.colors", "suffix": ""}, "value": {"path": "$.amount", "format": "number", "suffix": " tokens"}}, "detail": {"metadata": [{"label": "Bounty ID", "path": "$.bounty_id", "render_as": "copy_id", "zone": "identity"}, {"label": "Posted By", "path": "$.poster_wallet", "render_as": "copy_id", "zone": "config"}, {"label": "Claimer", "path": "$.claimer_wallet", "render_as": "copy_id", "zone": "config"}, {"label": "Reward", "path": "$.amount", "zone": "identity"}, {"label": "Activity", "path": "$.activity_count", "zone": "identity"}, {"label": "Last Activity", "path": "$.last_activity_label", "zone": "config"}, {"label": "Criteria", "path": "$.criteria", "render_as": "popover", "zone": "config"}, {"label": "Escrow TX", "path": "$.escrow_tx_id", "render_as": "copy_id", "zone": "identity"}, {"label": "Release TX", "path": "$.release_tx_id", "render_as": "copy_id", "zone": "identity"}, {"label": "Created", "path": "$.created_at", "render_as": "relative_time", "zone": "identity"}], "tabs": [{"id": "poster", "label": "Poster", "tool": "blockchain_get_wallet", "args": {"wallet_id": "$.poster_wallet"}, "render_as": "json"}, {"id": "claimer", "label": "Claimer", "tool": "blockchain_get_wallet", "args": {"wallet_id": "$.claimer_wallet"}, "render_as": "json"}, {"id": "activity", "label": "Activity", "tool": "blockchain_get_activity", "args": {"bounty_id": "$.bounty_id", "limit": 12}, "data_path": "$.entries", "render_as": "list", "empty_message": "No recorded activity for this bounty yet."}, {"id": "graph", "label": "Graph", "tool": "blockchain_get_entity_graph_context", "args": {"entity_id": "$.bounty_id", "limit": 12}, "data_path": "$.entries", "render_as": "list", "empty_message": "No related graph entities found for this bounty yet."}]}}}


def _tx_mix_chart() -> dict[str, Any]:
    return {"id": "bc-tx-mix", "type": "chart", "props": {"title": "Transaction Type Mix", "data_tool": "blockchain_get_dashboard_summary", "xKey": "label", "yKey": "value", "empty_state": "Create a wallet or move tokens to populate the ledger overview.", "className": "mb-3"}}


def _activity_stream() -> dict[str, Any]:
    return {"id": "bc-activity-stream", "type": "item_list", "props": {"data_tool": "blockchain_get_dashboard_summary", "data_path": "$.recent_activity", "item_key": "event_id", "empty_icon": "pulse", "empty_message": "No blockchain activity recorded yet.", "header": {"icon": "pulse", "stats_tool": "blockchain_get_dashboard_summary", "stats_map": {"activity": "$.overview.activity", "tx": "$.overview.transactions"}}, "filters": {"field": "event_type", "values": ["blockchain.wallet.created", "blockchain.tx.committed", "blockchain.bounty.posted", "blockchain.bounty.claimed", "blockchain.bounty.cancelled"], "colors": {"blockchain.wallet.created": "blue", "blockchain.tx.committed": "emerald", "blockchain.bounty.posted": "amber", "blockchain.bounty.claimed": "violet", "blockchain.bounty.cancelled": "red"}, "show_counts": False}, "item_layout": {"title": "$.label", "subtitle": "$.entity_id", "badge": {"field": "event_type", "color_map": "filters.colors", "suffix": ""}, "value": {"path": "$.age_label", "format": "text"}}, "detail": {"metadata": [{"label": "Entity", "path": "$.entity_id", "render_as": "copy_id", "zone": "identity"}, {"label": "TX", "path": "$.tx_id", "render_as": "copy_id", "zone": "identity"}, {"label": "Bounty", "path": "$.bounty_id", "render_as": "copy_id", "zone": "identity"}, {"label": "From", "path": "$.from_wallet", "render_as": "copy_id", "zone": "config"}, {"label": "To", "path": "$.to_wallet", "render_as": "copy_id", "zone": "config"}, {"label": "Detail", "path": "$.detail", "render_as": "popover", "zone": "config"}, {"label": "Timestamp", "path": "$.timestamp", "render_as": "relative_time", "zone": "identity"}]}}}


def _graph_context_stream() -> dict[str, Any]:
    return {"id": "bc-graph-context", "type": "item_list", "props": {"data_tool": "blockchain_get_dashboard_summary", "data_path": "$.related_graph_entities", "item_key": "entity_id", "empty_icon": "network", "empty_message": "No related graph entities yet.", "header": {"icon": "network", "stats_tool": "blockchain_get_dashboard_summary", "stats_map": {"entities": "$.overview.graph_entities", "tx": "$.overview.transactions"}}, "filters": {"field": "entity_type", "values": ["Wallet", "Transaction", "Bounty", "Block", "WorkflowRun", "Metric", "Finding"], "colors": {"Wallet": "blue", "Transaction": "emerald", "Bounty": "amber", "Block": "slate", "WorkflowRun": "violet", "Metric": "sky", "Finding": "red"}, "show_counts": False}, "item_layout": {"title": "$.title", "subtitle": "$.subtitle", "badge": {"field": "entity_type", "color_map": "filters.colors", "suffix": ""}, "value": {"path": "$.focus_entity_id", "format": "text"}}, "detail": {"metadata": [{"label": "Entity", "path": "$.entity_id", "render_as": "copy_id", "zone": "identity"}, {"label": "Type", "path": "$.entity_type", "render_as": "pills", "zone": "identity"}, {"label": "Focus", "path": "$.focus_entity_id", "render_as": "copy_id", "zone": "identity"}, {"label": "Detail", "path": "$.detail", "render_as": "popover", "zone": "config"}, {"label": "Properties", "path": "$.properties", "render_as": "popover", "zone": "config"}]}}}
