"""Persistence port for Workflow loop policy and cycle linkage."""
from __future__ import annotations

from typing import Protocol

from .loop_models import (
    CycleDisposition, CycleState, LoopCycleRecord, LoopRecord, LoopState,
)


class LoopStore(Protocol):
    def create_loop(self, record: LoopRecord) -> LoopRecord: ...
    def get_loop(self, tenant_id: str, owner_id: str,
                 loop_id: str) -> LoopRecord | None: ...
    def list_loops(self, tenant_id: str, owner_id: str,
                   limit: int = 100) -> list[LoopRecord]: ...
    def set_loop_state(self, record: LoopRecord, state: LoopState,
                       reason: str | None, expected_revision: int) -> LoopRecord | None: ...
    def create_cycle(self, record: LoopCycleRecord) -> LoopCycleRecord: ...
    def get_cycle(self, tenant_id: str, owner_id: str, loop_id: str,
                  cycle: int) -> LoopCycleRecord | None: ...
    def list_cycles(self, state: CycleState, limit: int = 100) -> list[LoopCycleRecord]: ...
    def set_cycle_state(self, record: LoopCycleRecord, state: CycleState,
                        workflow_run_id: str | None,
                        expected_revision: int) -> LoopCycleRecord | None: ...

    def settle_cycle(self, loop: LoopRecord, cycle: LoopCycleRecord,
                     disposition: CycleDisposition, summary: str,
                     blocker_digest: str | None, sentinel: bool): ...
    def mark_blocker_projected(self, record: LoopRecord,
                               expected_revision: int) -> LoopRecord | None: ...
    def list_unprojected_blockers(self, limit: int = 100) -> list[LoopRecord]: ...

__all__ = ["LoopStore"]
