"""Drift guard for the palette's real-schema fixture (bd:3jcls.4).

The frontend schema-to-form test (``__tests__/schema-form.test.ts``) must run
against schemas the repo REALLY ships, not a hand-written fixture — anti-drift
condition 4. So the fixture is generated by
``scripts/dump_real_tool_schemas.py`` and this test asserts it still matches
what the live bricks expose. If someone changes ``cache_set``'s signature or
``telemetry_record_log``'s ``Literal``, this fails with the regeneration
command instead of the frontend test quietly validating a stale shape.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from factory.mcp_server.runtime.lazy_loader import LazyBrickLoader
from factory.mcp_server.runtime.tool_catalog import build_tool_catalog

_FIXTURE = (
    Path(__file__).resolve().parents[5]
    / "frontends/next-dashboard/__tests__/fixtures/real-tool-schemas.json"
)
_REGEN = "uv run python scripts/dump_real_tool_schemas.py"


class _Agg:
    def __init__(self, lazy: object) -> None:
        self._lazy = lazy


@pytest.fixture(scope="module")
def fixture_tools() -> list[dict]:
    assert _FIXTURE.exists(), f"missing {_FIXTURE} — run: {_REGEN}"
    return json.loads(_FIXTURE.read_text())["tools"]


@pytest.fixture(scope="module")
def live_tools(fixture_tools: list[dict]) -> dict[str, dict]:
    loader = LazyBrickLoader()
    loader.set_available(sorted({t["brick"] for t in fixture_tools}))
    catalog = build_tool_catalog(_Agg(loader), ["operational", "authoring"])
    assert not catalog["bricks_failed"], catalog["bricks_failed"]
    return {t["qualified_name"]: t for t in catalog["tools"]}


def test_fixture_schemas_match_live_bricks(
    fixture_tools: list[dict], live_tools: dict[str, dict],
) -> None:
    for expected in fixture_tools:
        name = expected["qualified_name"]
        assert name in live_tools, (
            f"{name} no longer exists — regenerate the fixture: {_REGEN}"
        )
        actual = live_tools[name]
        assert actual["input_schema"] == expected["input_schema"], (
            f"{name} input_schema drifted from the fixture the frontend "
            f"schema-to-form test asserts against. Regenerate: {_REGEN}"
        )
        # dict equality ignores key order, but property order IS the order the
        # generated form renders fields in. Pin it explicitly.
        assert list(actual["input_schema"].get("properties", {})) == list(
            expected["input_schema"].get("properties", {})
        ), f"{name} param ORDER drifted (form field order). Regenerate: {_REGEN}"
        assert actual["category"] == expected["category"], (
            f"{name} category drifted. Regenerate: {_REGEN}"
        )


def test_fixture_still_covers_every_form_branch(fixture_tools: list[dict]) -> None:
    """The fixture is only useful if it exercises each derivation branch."""
    schemas = {t["qualified_name"]: t["input_schema"] for t in fixture_tools}
    blob = json.dumps(schemas)
    assert '"enum"' in blob, "no enum param left — pick another tool"
    assert '"integer"' in blob, "no numeric param left — pick another tool"
    assert '"default"' in blob, "no defaulted param left — pick another tool"
    assert '"null"' in blob, "no nullable param left — pick another tool"
    assert any(s.get("required") for s in schemas.values()), "no required params"
    assert any(not s.get("properties") for s in schemas.values()), (
        "no zero-argument tool left — the empty-form path is untested"
    )
