"""App deploy agent addenda — deploy real CFN + code from workspace files.

Reads CFN templates and Lambda code from the sandbox workspace
directory (written by code-discovery). Falls back to direct
resource creation from recon.json if no CFN template exists.
Only AppDeployment status is written to graph (curated).
"""
from __future__ import annotations

_WS = "/tmp/factory-sandbox/{env_id}/artifacts"

APP_DEPLOY = (
    "\n== APP DEPLOYMENT (Real CFN + Code) ==\n"
    "Deploy actual app artifacts from workspace files into\n"
    "the LocalStack sandbox.\n\n"
    "STEP 1 — Deploy real CFN (if available):\n"
    "  Check for CFN template in workspace:\n"
    "  sandbox.execute(env_id,\n"
    f"    'cat {_WS}/cfn-template.yaml')\n"
    "  If file exists and has content:\n"
    "    First translate for LocalStack compatibility:\n"
    "    sandbox.translate_cfn(\n"
    "      template_body=<content>, mode='security')\n"
    "    Then deploy:\n"
    "    sandbox.deploy_cfn(env_id,\n"
    "      stack_name='{{target_app}}-stack',\n"
    "      template_body=<filtered_template>)\n"
    "    Check stack status:\n"
    "    sandbox.describe_stack(env_id,\n"
    "      stack_name='{{target_app}}-stack')\n"
    "  If NOT found → fall back to direct resource creation\n"
    "    from recon.json:\n"
    "    sandbox.execute(env_id,\n"
    f"      'cat {_WS}/recon.json')\n"
    "    Create resources directly from the resources list.\n\n"
    "STEP 2 — Deploy app code:\n"
    "  Check what code files exist:\n"
    "  sandbox.execute(env_id,\n"
    f"    'ls {_WS}/code/')\n"
    "  For Python Lambdas:\n"
    "    Zip and deploy as Lambda function code:\n"
    "    sandbox.execute(env_id,\n"
    f"      'cd {_WS}/code && "
    "zip -r /tmp/app.zip . && "
    "aws lambda update-function-code "
    "--function-name <name> "
    "--zip-file fileb:///tmp/app.zip')\n"
    "  For Java Lambdas:\n"
    "    Install JRE if needed, compile or use as-is.\n"
    "    Create stub Lambda — LocalStack does not need\n"
    "    compiled JARs for basic invocation testing.\n"
    "    IDOR/authz vulns are in the IAM layer.\n"
    "  For any runtime:\n"
    "    Create Lambda function with the real handler code.\n\n"
    "STEP 3 — Seed test data:\n"
    "  Read recon.json for table schemas:\n"
    "  sandbox.execute(env_id,\n"
    f"    'cat {_WS}/recon.json')\n"
    "  For each DynamoDB table, seed at least 2 users\n"
    "  (user-A, user-B) for IDOR testing:\n"
    "  sandbox.execute(env_id,\n"
    "    'aws dynamodb put-item --table-name <name> "
    '--item {{"pk":{{"S":"user-A#data"}},...}}\')\n'
    "  sandbox.execute(env_id,\n"
    "    'aws dynamodb put-item --table-name <name> "
    '--item {{"pk":{{"S":"user-B#data"}},...}}\')\n\n'
    "STEP 4 — Record deployment (graph — curated):\n"
    "  graph_add_entity(\n"
    "    entity_id='app-deploy-{{run_id}}',\n"
    "    entity_type='AppDeployment',\n"
    "    properties={\n"
    "      run_id: '{{run_id}}', app: '{{target_app}}',\n"
    "      cfn_deployed: true/false,\n"
    "      lambdas_deployed: ['<name1>', '<name2>'],\n"
    "      data_seeded: true/false,\n"
    "      source: 'workspace-files'\n"
    "    })\n"
)
