"""Code discovery agent addenda — download real code into sandbox.

Downloads code from Brazil packages directly into the LocalStack
container using curl + Midway cookie. Simple and reliable.
"""
from __future__ import annotations

_WS = "/tmp/factory-sandbox/companion_x-localstack-1/artifacts"
_CURL = "curl -sfL -b /root/.midway/cookie"
_RAW = "?raw=true"
_CODE = "https://code.amazon.com/packages"

CODE_DISCOVERY = (
    "\n== CODE DISCOVERY (Real CFN + Lambda Source) ==\n"
    "Download code from Brazil directly into the sandbox\n"
    "using curl + Midway cookie. Simple, no context issues.\n\n"
    "CRITICAL: For downloading files, ONLY use sandbox.execute\n"
    "with curl. Do NOT use builder_read_package_file or any\n"
    "builder tool to read file content — those return HTML, not\n"
    "raw source. The ONLY reliable path is:\n"
    f"  sandbox.execute(env_id, '{_CURL} \"<url>{_RAW}\" -o <dest>')\n\n"
    "You MAY use builder_list_package_files to discover file paths,\n"
    "and get_deployment_chain to find packages. But ALL file\n"
    "downloads MUST go through sandbox.execute + curl.\n\n"
    "STEP 0 — Clean workspace code dir:\n"
    f"  sandbox.execute(env_id, 'rm -rf {_WS}/code && "
    f"mkdir -p {_WS}/code')\n\n"
    "STEP 1 — Get deployment chain:\n"
    "  get_deployment_chain(identifier='{{target_app}}')\n"
    "  Find pipelines. Classify: Infrastructure vs Code.\n\n"
    "STEP 2 — List files in each package:\n"
    "  builder_list_package_files(package_name='<pkg>')\n"
    "  Identify CFN templates and source code files.\n\n"
    "STEP 3 — Download files via curl:\n"
    "  For each file, run ONE sandbox.execute command:\n"
    "  sandbox.execute(env_id,\n"
    f"    '{_CURL} \"{_CODE}/<pkg>/blobs/mainline/--/"
    f"<file_path>{_RAW}\" -o {_WS}/code/<filename>')\n\n"
    "  Examples:\n"
    "  # Download CFN template\n"
    "  sandbox.execute(env_id,\n"
    f"    '{_CURL} \"{_CODE}/<InfraPkg>/blobs/mainline/--/"
    "configuration/cloudFormation/<tpl>.yml"
    f"{_RAW}\" -o {_WS}/cfn-template.yaml')\n\n"
    "  # Download Java handler\n"
    "  sandbox.execute(env_id,\n"
    f"    '{_CURL} \"{_CODE}/<CodePkg>/blobs/mainline/--/"
    "src/<path>/<Handler>.java"
    f"{_RAW}\" -o {_WS}/code/<Handler>.java')\n\n"
    "  # Download build file\n"
    "  sandbox.execute(env_id,\n"
    f"    '{_CURL} \"{_CODE}/<CodePkg>/blobs/mainline/--/"
    f"build.xml{_RAW}\" -o {_WS}/build.xml')\n\n"
    "STEP 4 — Verify downloads:\n"
    f"  sandbox.execute(env_id, 'ls -la {_WS}/ && "
    f"ls -la {_WS}/code/')\n"
    "  Confirm files exist with non-zero size.\n\n"
    "  Do NOT write anything to graph. All scratchpad.\n"
)
