"""Import-to-package mapping and stdlib filter for dependency resolution.

Single source of truth for mapping Python import names to pip package
specs.  Used by ``deps.py`` (scanner) and ``deps_sync.py`` (writer).
"""

# Map of top-level import names to pip package specs.
IMPORT_TO_PACKAGE: dict[str, str] = {
    "aiohttp": "aiohttp>=3.9.0",
    "aiosqlite": "aiosqlite>=0.19.0",
    "anthropic": "anthropic>=0.34.0",
    "apprise": "apprise>=1.9.0",
    "asammdf": "asammdf>=8.0.0",
    "authlib": "authlib>=1.3.0",
    "aws_bedrock_token_generator": "aws-bedrock-token-generator>=1.1.0",
    "blinker": "blinker>=1.9.0",
    "boto3": "boto3>=1.35.0",
    "botocore": "botocore>=1.34,<2",
    "cantools": "cantools>=42.0.0",
    "cedarpy": "cedarpy>=0.4.0",
    "celery": "celery>=5.6.2",
    "chromadb": "chromadb>=1.4.1",
    "click": "click>=8.0.0",
    "cognee": "cognee>=0.1.0",
    "cryptography": "cryptography>=44.0.0",
    "dagster": "dagster>=1.7.0",
    "fastapi": "fastapi>=0.128.0",
    "fasthtml": "python-fasthtml>=0.12.39",
    "flet": "flet>=0.85.3",
    "flet_charts": "flet-charts>=0.1.0",
    "gql": "gql[httpx]>=3.5.0",
    "hfc": "fabric-sdk-py>=1.0.0",
    "httpx": "httpx>=0.27.0",
    "hypothesis": "hypothesis>=6.0.0",
    "jinja2": "jinja2>=3.1.0",
    "joblib": "joblib>=1.3.0",
    "jwt": "pyjwt[crypto]>=2.8.0",
    "lightgbm": "lightgbm>=4.0.0",
    "mcp": "mcp[cli]==2.1.1",
    "mlflow": "mlflow>=2.14.0",
    "neo4j": "neo4j>=6.1.0",
    "neo4j_graphrag": "neo4j-graphrag>=1.0.0",
    "networkx": "networkx>=3.6.1",
    "numpy": "numpy>=1.24.0",
    "openai": "openai>=1.40.0",
    "opentelemetry": "opentelemetry-api>=1.20.0",
    "pandas": "pandas>=2.0.0",
    "psycopg2": "psycopg2-binary>=2.9.9",
    "pydantic": "pydantic>=2.0.0",
    "pydantic_settings": "pydantic-settings>=2.12.0",
    "pymongo": "pymongo>=4.8.0",
    "rank_bm25": "rank-bm25>=0.2.2",
    "rapidfuzz": "rapidfuzz>=3.0.0",
    "redis": "redis>=7.1.0",
    "sdv": "sdv>=1.37.0",
    "sklearn": "scikit-learn>=1.3.0",
    "starlette": "starlette>=0.40.0",
    "stripe": "stripe>=14.3.0a1",
    "structlog": "structlog>=25.1.0",
    "tenacity": "tenacity>=8.2.0",
    "tensorboard": "tensorboard>=2.17.0",
    "tinydb": "tinydb>=4.8.2",
    "tomli": "tomli>=2.0.0; python_version<'3.11'",
    "torch": "torch>=2.3.0",
    "typer": "typer>=0.12.0",
    "uvicorn": "uvicorn>=0.40.0",
    "websockets": "websockets>=12.0",
    "yaml": "pyyaml>=6.0.0",
    "zep_cloud": "zep-cloud>=2.0.0",
}

# Standard library modules — skip these during import scanning.
STDLIB = {
    "abc", "argparse", "ast", "asyncio", "base64", "collections",
    "contextlib", "copy", "dataclasses", "datetime", "enum", "fnmatch",
    "functools", "hashlib", "hmac", "importlib", "inspect", "io", "itertools",
    "json", "logging", "math", "os", "pathlib", "pickle", "platform",
    "random", "re", "shutil", "socket", "sqlite3", "string", "subprocess",
    "sys", "tempfile", "threading", "time", "traceback", "typing",
    "unittest", "urllib", "uuid", "warnings", "weakref", "xml", "zipfile",
    "__future__", "typing_extensions", "concurrent", "multiprocessing",
    "http", "html", "email", "secrets", "struct", "textwrap", "operator",
    "numbers", "decimal", "fractions", "statistics", "cmath", "array",
    "bisect", "heapq", "queue", "types", "contextvars", "graphlib",
    "difflib", "glob", "signal", "site", "sysconfig", "token", "tokenize",
    "tomllib",
}
