"""Docker scaffolding — generates Dockerfile and docker-compose.yml.

Polymorphic: detects which bases are wired and generates appropriate
services. Infra services are driven by brick adapter requirements.
"""

from pathlib import Path

# Base → service config (port, cmd, compose service name suffix)
BASE_SERVICES: dict[str, dict] = {
    "api": {
        "port": 8000,
        "cmd": '["uvicorn", "factory.mcp_server.core:create_app", "--host", "0.0.0.0", "--port", "8000", "--factory"]',
        "suffix": "api",
    },
    "worker": {
        "port": None,
        "cmd": '["python", "-m", "factory.worker.main"]',
        "suffix": "worker",
    },
    "mcp_server": {
        "port": None,
        "cmd": '["python", "-m", "factory.mcp_server.core"]',
        "suffix": "mcp",
    },
}

# Brick → infra service requirements (image, ports, env, volumes)
BRICK_INFRA: dict[str, dict] = {
    "cache": {
        "service": "redis",
        "image": "redis:7-alpine",
        "ports": ["6379:6379"],
    },
    "events": {
        "service": "redis",
        "image": "redis:7-alpine",
        "ports": ["6379:6379"],
    },
    "graph": {
        "service": "neo4j",
        "image": "neo4j:5-community",
        "ports": ["7474:7474", "7687:7687"],
        "environment": {"NEO4J_AUTH": "neo4j/password"},
        "volumes": ["neo4j_data:/data"],
    },
    "kb": {
        "service": "chromadb",
        "image": "chromadb/chroma:latest",
        "ports": ["8100:8000"],
        "volumes": ["chroma_data:/chroma/data"],
    },
    "storage": {
        "service": "postgres",
        "image": "postgres:16-alpine",
        "ports": ["5432:5432"],
        "environment": {
            "POSTGRES_USER": "factory",
            "POSTGRES_PASSWORD": "factory",
            "POSTGRES_DB": "factory",
        },
        "volumes": ["postgres_data:/var/lib/postgresql/data"],
    },
    "auth": {
        "service": "keycloak",
        "image": "quay.io/keycloak/keycloak:24.0",
        "ports": ["8080:8080"],
        "environment": {
            "KC_BOOTSTRAP_ADMIN_USERNAME": "admin",
            "KC_BOOTSTRAP_ADMIN_PASSWORD": "admin",
        },
        "command": "start-dev",
    },
    "workflow": {
        "service": "dagster",
        "image": "dagster/dagster-celery-k8s:latest",
        "ports": ["3000:3000"],
        "environment": {"DAGSTER_HOME": "/opt/dagster/dagster_home"},
    },
    "telemetry": {
        "service": "phoenix",
        "image": "arizephoenix/phoenix:latest",
        "ports": ["6006:6006"],
    },
}


def generate_dockerfile(name: str, bases: list[str]) -> str:
    """Generate a multi-stage Dockerfile for the project."""
    primary = bases[0] if bases else "mcp_server"
    cmd = BASE_SERVICES.get(primary, BASE_SERVICES["mcp_server"])["cmd"]
    ports = " ".join(
        str(BASE_SERVICES[b]["port"]) for b in bases
        if BASE_SERVICES.get(b, {}).get("port")
    )

    return f"""# Auto-generated by foreman — {name}
FROM python:3.12-slim AS base
WORKDIR /app
RUN pip install --no-cache-dir uv

FROM base AS deps
COPY projects/{name}/pyproject.toml .
RUN uv pip install --system -r pyproject.toml 2>/dev/null || true

FROM deps AS src
COPY components/ /workspace/components/
COPY bases/ /workspace/bases/
COPY projects/{name}/ /workspace/projects/{name}/
COPY BRICKS_INDEX.yaml /workspace/BRICKS_INDEX.yaml
WORKDIR /workspace
# NOT editable (bd:python-factory-9fewj). An editable install of a project
# that declares [tool.hatch.build] dev-mode-dirs emits a .pth pointing at
# /workspace/{{components,bases}}/*/src, and the runtime stage below discards
# /workspace — so the bricks would vanish at CMD. A standard wheel keeps the
# composed bricks inside site-packages, which is what gets copied forward.
RUN uv pip install --system --no-deps projects/{name}/

FROM python:3.12-slim AS runtime
WORKDIR /app
COPY --from=src /usr/local/lib/python3.12/site-packages /usr/local/lib/python3.12/site-packages
COPY --from=src /usr/local/bin /usr/local/bin
COPY --from=src /workspace/BRICKS_INDEX.yaml /app/BRICKS_INDEX.yaml
ENV WORKSPACE_ROOT=/app
EXPOSE {ports}
CMD {cmd}
"""


def _collect_infra(bricks: list[str]) -> tuple[dict[str, dict], set[str]]:
    """Deduplicate infra services needed by the wired bricks."""
    services: dict[str, dict] = {}
    volumes: set[str] = set()
    for brick in bricks:
        infra = BRICK_INFRA.get(brick)
        if not infra or infra["service"] in services:
            continue
        services[infra["service"]] = {
            k: infra[k] for k in ("image", "ports", "environment", "command", "volumes")
            if k in infra
        }
        for v in infra.get("volumes", []):
            volumes.add(v.split(":")[0])
    return services, volumes


def _render_svc(lines: list[str], name: str, props: dict) -> None:
    """Append a single compose service block to lines."""
    lines.append(f"  {name}:")
    for key in ("image", "command"):
        if key in props:
            lines.append(f"    {key}: {props[key]}")
    if "build" in props:
        lines.append("    build:")
        for k, v in props["build"].items():
            lines.append(f"      {k}: {v}")
    if "environment" in props:
        lines.append("    environment:")
        for k, v in props["environment"].items():
            lines.append(f"      {k}: {v}")
    for key in ("ports", "volumes", "env_file", "depends_on"):
        if key in props:
            lines.append(f"    {key}:")
            for item in props[key]:
                q = f'"{item}"' if key == "ports" else item
                lines.append(f"      - {q}")


def generate_compose(name: str, bases: list[str], bricks: list[str]) -> str:
    """Generate docker-compose.yml for the project."""
    infra, volumes = _collect_infra(bricks)
    infra_names = sorted(infra.keys())
    lines = [f"# Auto-generated by foreman — {name}", "services:"]

    for svc_name, svc in sorted(infra.items()):
        _render_svc(lines, svc_name, svc)

    for base in bases:
        cfg = BASE_SERVICES.get(base)
        if not cfg:
            continue
        props: dict = {
            "build": {"context": "../..", "dockerfile": f"projects/{name}/Dockerfile"},
            "command": cfg["cmd"],
            "env_file": [".env"],
        }
        if cfg["port"]:
            props["ports"] = [f"{cfg['port']}:{cfg['port']}"]
        if infra_names:
            props["depends_on"] = infra_names
        _render_svc(lines, f"{name}-{cfg['suffix']}", props)

    if volumes:
        lines += ["", "volumes:"] + [f"  {v}:" for v in sorted(volumes)]
    return "\n".join(lines) + "\n"
