"""Makefile and .env.example scaffolding for projects.

Generates standardized commands: dev, up, stop, logs, test.
Env vars are driven by which bricks are wired.
"""

# Brick → env vars needed at runtime
BRICK_ENV_VARS: dict[str, list[tuple[str, str]]] = {
    "auth": [
        ("FACTORY_AUTH_ADAPTER", "memory"),
        ("KEYCLOAK_URL", "http://localhost:8080"),
        ("KEYCLOAK_REALM", "factory"),
        ("KEYCLOAK_CLIENT_ID", "factory-app"),
        ("KEYCLOAK_CLIENT_SECRET", "change-me"),
    ],
    "cache": [
        ("FACTORY_CACHE_ADAPTER", "memory"),
        ("REDIS_URL", "redis://localhost:6379/0"),
    ],
    "events": [
        ("FACTORY_EVENTS_ADAPTER", "memory"),
        ("REDIS_URL", "redis://localhost:6379/0"),
    ],
    "graph": [
        ("FACTORY_GRAPH_ADAPTER", "networkx"),
        ("NEO4J_URI", "bolt://localhost:7687"),
        ("NEO4J_USER", "neo4j"),
        ("NEO4J_PASSWORD", "password"),
    ],
    "kb": [
        ("FACTORY_KB_ADAPTER", "local"),
        ("CHROMA_HOST", "localhost"),
        ("CHROMA_PORT", "8100"),
    ],
    "storage": [
        ("FACTORY_STORAGE_ADAPTER", "memory"),
        ("POSTGRES_DSN", "postgresql://factory:factory@localhost:5432/factory"),
        ("AWS_S3_BUCKET", "factory-storage"),
    ],
    "llm_gateway": [
        ("FACTORY_LLM_ADAPTER", "bedrock"),
        ("AWS_DEFAULT_REGION", "us-east-1"),
        ("OPENAI_API_KEY", ""),
        ("ANTHROPIC_API_KEY", ""),
    ],
    "telemetry": [
        ("OTEL_EXPORTER_OTLP_ENDPOINT", "http://localhost:6006"),
        ("OTEL_SERVICE_NAME", "factory"),
    ],
    "memory": [
        ("FACTORY_MEMORY_ADAPTER", "memory"),
    ],
    "workflow": [
        ("FACTORY_WORKFLOW_ADAPTER", "memory"),
        ("DAGSTER_HOME", "/opt/dagster/dagster_home"),
    ],
    "notification": [
        ("FACTORY_NOTIFICATION_ADAPTER", "stdio"),
    ],
    "security": [
        ("FACTORY_SECURITY_ADAPTER", "mock"),
    ],
    "integrations": [
        ("FACTORY_INTEGRATIONS_ADAPTER", "rest"),
    ],
}

# Base → env vars
BASE_ENV_VARS: dict[str, list[tuple[str, str]]] = {
    "api": [
        ("FACTORY_API_HOST", "0.0.0.0"),
        ("FACTORY_API_PORT", "8000"),
    ],
    "worker": [
        ("FACTORY_WORKER_BACKEND", "celery"),
        ("FACTORY_CELERY_BROKER_URL", "redis://localhost:6379/1"),
    ],
    "mcp_server": [
        ("MCP_SERVER_NAME", "factory-app"),
        ("MCP_INCLUDE_BRICKS", ""),
        ("MCP_EXCLUDE_BRICKS", ""),
    ],
}


def generate_makefile(name: str, bases: list[str]) -> str:
    """Generate a project-level Makefile with standard commands."""
    app_services = " ".join(f"{name}-{_suffix(b)}" for b in bases if _suffix(b))

    return f"""# Auto-generated by foreman — {name}
.PHONY: help up stop dev logs test build

help:
\t@echo "Project: {name}"
\t@echo "  make up    — Start everything (infra + app)"
\t@echo "  make stop  — Stop everything"
\t@echo "  make dev   — Start infra only (for local app dev)"
\t@echo "  make logs  — Tail app logs"
\t@echo "  make test  — Run project tests"
\t@echo "  make build — Build Docker images"

up:
\tcp -n .env.example .env 2>/dev/null || true
\tdocker compose up -d

stop:
\tdocker compose down

dev:
\tcp -n .env.example .env 2>/dev/null || true
\tdocker compose up -d $$(docker compose config --services | grep -v '{name}')

logs:
\tdocker compose logs -f {app_services}

test:
\tuv run --project . pytest

build:
\tdocker compose build {app_services}
"""


def _suffix(base: str) -> str:
    """Map base name to compose service suffix."""
    return {"api": "api", "worker": "worker", "mcp_server": "mcp"}.get(base, base)


def generate_env_example(name: str, bases: list[str], bricks: list[str]) -> str:
    """Generate .env.example with all env vars for wired bricks."""
    lines = [f"# Auto-generated by foreman — {name}", f"# Copy to .env and fill in values", ""]

    # Base env vars
    for base in sorted(bases):
        env_vars = BASE_ENV_VARS.get(base, [])
        if env_vars:
            lines.append(f"# --- {base} base ---")
            for key, default in env_vars:
                lines.append(f"{key}={default}")
            lines.append("")

    # Brick env vars
    for brick in sorted(bricks):
        env_vars = BRICK_ENV_VARS.get(brick, [])
        if env_vars:
            lines.append(f"# --- {brick} ---")
            for key, default in env_vars:
                lines.append(f"{key}={default}")
            lines.append("")

    return "\n".join(lines)
