"""Generate kirocrew-feature-map.md from the upstream KiroCrew feature map.

Upstream: https://github.com/kirodotdev/kirocrew  docs/feature-map/README.md
Local read-only clone: /Users/wdaniero/workplace/kirocrew-workspace/kirocrew-src

Re-run after `git -C <clone> pull --ff-only`. Existing Status/Evidence/Location
cells are preserved by feature name so the loop's progress is never lost.

    uv run python .kiro/specs/python-factory-bp34j-companion-crew-features/scripts/gen_kirocrew_feature_map.py
"""
from __future__ import annotations

import pathlib
import re
import subprocess

SRC = pathlib.Path("/Users/wdaniero/workplace/kirocrew-workspace/kirocrew-src")
SPEC = pathlib.Path(__file__).resolve().parents[1]
OUT = SPEC / "kirocrew-feature-map.md"

# Owner IA decisions (2026-09-13 19:23): where each upstream area lives in Companion-X.
HOME = {
    "Chat and sessions": "Chat sidebar + rail **Sessions** (Operations)",
    "Agent Capabilities": "rail **Agent Capabilities** (single icon, sub-nav inside)",
    "Memory, lessons and usage": "Settings → Overview/Usage; Lessons under Agent Capabilities",
    "Schedules and loops": "Agent Capabilities → **Schedules** (no own rail icon — owner decision)",
    "Artifacts": "Agent Capabilities → **Artifacts** (no own rail icon — owner decision)",
    "Apps": "OWNER DECISION PENDING (Agent Capabilities → Apps, or OWNER_NA)",
    "Task runner and subagents": "Agent Capabilities → Agent Templates (subagents table) + Terminal panel",
    "Settings": "rail **Settings** gear (single icon, full suite inside)",
    "Developer": "Settings → Developer",
    "Standalone operator surfaces": "Settings → Developer / Terminal panel (case by case)",
    "Popouts and embeds": "case by case; chat popout + artifact embed first",
    "Redirects": "N/A unless a Companion-X route is renamed",
}
SKIP = {"Maintenance contract", "How to read this"}
STATUS_RE = re.compile(r"^\| *\d+ \| (?P<feat>[^|]+)\|.*\| (?P<loc>[^|]*)\| (?P<status>[^|]*)\| (?P<ev>[^|]*)\|$")


def previous_progress() -> dict[tuple[str, str], tuple[str, str, str]]:
    """(area, feature) -> (location, status, evidence) from the current file, if any.

    Keyed by area too: upstream has same-named rows in different areas (Hooks, Logs, Webhooks).
    """
    keep: dict[tuple[str, str], tuple[str, str, str]] = {}
    if not OUT.exists():
        return keep
    area = ""
    for ln in OUT.read_text().splitlines():
        if ln.startswith("## "):
            area = ln[3:].strip()
            continue
        m = STATUS_RE.match(ln.strip())
        if m:
            keep[(area, m["feat"].strip())] = (m["loc"].strip(), m["status"].strip(), m["ev"].strip())
    return keep


def main() -> None:
    commit = subprocess.check_output(
        ["git", "-C", str(SRC), "log", "-1", "--format=%h %cd", "--date=short"], text=True
    ).strip()
    upstream = (SRC / "docs/feature-map/README.md").read_text().splitlines()
    keep = previous_progress()

    lines: list[str] = [
        "# KiroCrew → Companion-X feature checklist (code-referenced)",
        "",
        f"Generated by `scripts/gen_kirocrew_feature_map.py` from upstream `docs/feature-map/README.md` "
        f"(https://github.com/kirodotdev/kirocrew) at commit `{commit}`.",
        f"Local read-only clone for code lookup: `{SRC}` (refresh: `git -C {SRC} pull --ff-only`, then re-run the generator; "
        "Status/Evidence/Location cells survive regeneration).",
        "",
        "**Never copy KiroCrew code.** Read the upstream page/handler to learn the behaviour, then implement it Python-Factory style: "
        "Polylith brick + MCP tool (strict Pydantic ingress, typed `ToolResult` egress), LangChain/LangGraph on MCP v2, CopilotKit v2, "
        "shadcn/ui, brick-declared views. Sidebar truth upstream is `website/src/surfaces/builtins.tsx`.",
        "",
        "## How the loop uses this file",
        "",
        "- **This is the M7.5 acceptance list.** Gate 0 counts rows; M7.5 cannot close while any row is `TODO`, `MISSING`, or `PRESENT+BROKEN`.",
        "- `Status` ∈ `TODO` (unchecked) · `MISSING` · `PRESENT+BROKEN` · `PRESENT+WORKS` (requires a screenshot path in `Evidence`) · "
        "`OWNER_NA` (never build) · `OWNER_DEFERRED` (owner wants it LATER — build in **M9 Deferred features**) · `OWNER_REBRAND` "
        "(KiroCrew-identity item — ditch or re-spec under Companion-X's own name/repo in **M8 Rebrand**). All three `OWNER_*` statuses "
        "are only valid in the owner's words, quoted in `Evidence`, and are OUT of M7.5 scope.",
        "- **Order after M7.5:** M8 Rebrand first (owner: \"rebrand/whatever last but before the deferred features\"), then M9 Deferred "
        "features (voice, channels/Slack, Remote Crew + webhooks, Brick Store replacing KiroCrew's app store).",
        "- **Cycle 1 of M7.5 is a census** (done 2026-09-13: 9 works / 33 broken / 98 missing). After that, work in **OWNER PRIORITY ORDER, "
        "not file order** (owner escalation 2026-09-13 22:10 — the loop spent three cycles polishing Sessions rows 1–2 while the suites the "
        "owner asked for stayed broken):",
        "  1. **Agent Capabilities** (Crews, Agent Templates, Connections, Skills, Steering, Hooks, Prompts — every tab must do its job, not show \"unavailable\")",
        "  2. **Settings** (all 21 rows: each section either works or is `OWNER_NA` in the owner's words)",
        "  3. **Task runner and subagents** — Terminal as a real PTY panel + subagents table",
        "  3b. **M7.6 Dogfood loop (roadmap)** — immediately after the Terminal rows and BEFORE any further Settings rows: make Companion-X's "
        "own goal loop drive an agent turn per cycle (rows 55, 58, 61) and prove it by completing one real checklist row with the KiroCrew loop off. "
        "This is the owner's #1 outcome; nothing else in M7.5 outranks it once Terminal is usable.",
        "  3c. **M7.7 Unified graph memory (roadmap)** — right after M7.6, built by Companion-X's own loop: Memory + KB onto the one persistent "
        "networkx graph with a light local embedder; rows 43–54 (Memory, lessons and usage) are its UI. Owner ruling 2026-09-15: never 'deferred'.",
        "  4. **Schedules and loops**, then **Artifacts**",
        "  5. **Chat and sessions** — remaining rows (tags, folders, forks, popouts are polish; do them last)",
        "  6. Developer · Standalone operator surfaces · Popouts and embeds · Apps (pending owner ruling) · Redirects",
        "- Within a priority area: `MISSING` rows before `PRESENT+BROKEN` rows whose missing piece is cosmetic. One row (or one tightly coupled "
        "group) per slice; update the row in the same cycle. A `PRESENT+BROKEN` row the owner can already use for daily work (e.g. Sessions) "
        "does not get another cycle while a higher-priority area has `MISSING` rows.",
        "- **Renders ≠ works.** `PRESENT+WORKS` means the control round-trips through the MCP tool and shows the result, not that the page loads. "
        "**Parity means the buttons too (owner 2026-09-15 07:52):** a row is `PRESENT+WORKS` only when EVERY user control on the upstream page exists and works — "
        "list AND create (+ / JSON import) AND edit AND delete AND apply/reload. A list-only tab is `PRESENT+BROKEN`. Owner: \"there's no + button for the user "
        "to add the thing the menu is talking about… wtf\". Reviewers must enumerate the upstream page's controls and tick each one.",
        "- `Reach it` / `Page` / `Handler` / `Endpoints` are **upstream KiroCrew** references (read them). `Companion-X location` is the "
        "route/component/brick here.",
        "- Every new or changed surface ships with one view-only Playwright screenshot on the 18000/13000 smoke stack (LOOP-GUIDE).",
        "",
        "## Owner IA decisions (2026-09-13 19:23)",
        "",
        "1. **Agent Capabilities is ONE rail icon** with a sub-nav inside: Crews · Agent Templates · Connections · Skills · Steering · Hooks · "
        "Prompts · **Schedules** · **Artifacts** · Lessons.",
        "2. **Settings is ONE gear icon** with the full suite inside: Overview · Import/Export · Chat · Display · Voice · Notifications · Shortcuts · "
        "Skills · Channels · Browser · Computer Use · Remote Crew · Privacy · Security · Developer · About (each row below decides PRESENT vs OWNER_NA).",
        "3. **Schedules and Artifacts lose their own rail icons** and move under Agent Capabilities (Kiro's pick between the two options the owner "
        "offered; owner may move them to Settings instead).",
        "4. Resulting rail: Sessions/Chat · existing Analysis/Intelligence canvases · Agent Capabilities · Settings · Terminal (dockable panel) · bell.",
        "",
        "---",
    ]

    area: str | None = None
    total = 0
    for ln in upstream:
        heading = re.match(r"^## (.+)$", ln)
        if heading:
            area = heading.group(1).strip()
            if area in SKIP:
                continue
            lines += [
                "",
                f"## {area}",
                "",
                f"Companion-X home: {HOME.get(area, 'TBD')}",
                "",
                "| # | Feature | What it is | Reach it (upstream) | Page (`website/src/`) | Handler (`src/kiro_crew/dashboard/`) | "
                "Endpoints (upstream) | Companion-X location | Status | Evidence |",
                "|---|---|---|---|---|---|---|---|---|---|",
            ]
            continue
        if area is None or area in SKIP:
            continue
        if ln.startswith("| ") and not re.match(r"^\| *(Feature|:?-{2,})", ln):
            cells = [c.strip() for c in ln.strip().strip("|").split("|")]
            cells += [""] * (6 - len(cells))
            total += 1
            loc, status, ev = keep.get((area, cells[0]), ("", "TODO", ""))
            lines.append("| " + " | ".join([str(total), *cells[:6], loc, status, ev]) + " |")
        elif ln.strip() and not ln.startswith("|") and not ln.startswith("#"):
            lines.append(ln)  # upstream prose notes give the loop context

    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT.relative_to(SPEC.parent.parent.parent)}: {total} feature rows")


if __name__ == "__main__":
    main()
