"""Persistence ports for tenant-owned sessions and steer delivery."""
from __future__ import annotations

from typing import Protocol

from .models import SessionRecord, SteerMessage, SteerState


class SessionStore(Protocol):
    def create(self, record: SessionRecord) -> SessionRecord: ...
    def get(self, tenant_id: str, owner_id: str, session_id: str) -> SessionRecord | None: ...
    def get_by_thread(self, tenant_id: str, owner_id: str, thread_id: str) -> SessionRecord | None: ...
    def list(self, tenant_id: str, owner_id: str, *, include_archived: bool = False) -> list[SessionRecord]: ...
    def rename(self, tenant_id: str, owner_id: str, session_id: str, title: str, expected_revision: int) -> SessionRecord | None: ...
    def set_archived(self, tenant_id: str, owner_id: str, session_id: str, archived: bool, expected_revision: int) -> SessionRecord | None: ...
    def set_project(self, tenant_id: str, owner_id: str, session_id: str,
                    project: str, expected_revision: int) -> SessionRecord | None: ...
    def set_model(self, tenant_id: str, owner_id: str, session_id: str,
                  model: str, expected_revision: int) -> SessionRecord | None: ...
    def set_pinned(self, tenant_id: str, owner_id: str, session_id: str,
                   pinned: bool, expected_revision: int) -> SessionRecord | None: ...
    def set_active_checkpoint(self, tenant_id: str, owner_id: str, session_id: str,
                              checkpoint_id: str | None, expected_revision: int) -> SessionRecord | None: ...
    def set_summary(self, tenant_id: str, owner_id: str, session_id: str,
                    summary: str, expected_revision: int) -> SessionRecord | None: ...
    def set_folder(self, tenant_id: str, owner_id: str, session_id: str,
                   folder: str, expected_revision: int) -> SessionRecord | None: ...
    def move_pinned(self, tenant_id: str, owner_id: str, session_id: str,
                    before_session_id: str | None,
                    expected_revision: int) -> SessionRecord | None: ...
    def set_tags(self, tenant_id: str, owner_id: str, session_id: str,
                 tags: tuple[str, ...], expected_revision: int) -> SessionRecord | None: ...
    def set_pinned_messages(self, tenant_id: str, owner_id: str, session_id: str,
                            pinned_message_ids: tuple[str, ...],
                            expected_revision: int) -> SessionRecord | None: ...
    def rebind(self, tenant_id: str, owner_id: str, session_id: str, crew_id: str,
               memory_scope: str, agent_id: str, model: str, project: str,
               workspace: str, expected_revision: int) -> SessionRecord | None: ...
    def delete(self, tenant_id: str, owner_id: str, session_id: str,
               expected_revision: int) -> bool: ...
    def count_archived(self, tenant_id: str, owner_id: str) -> int: ...
    def delete_archived(self, tenant_id: str, owner_id: str) -> int: ...


class SteerMailbox(Protocol):
    def append(self, message: SteerMessage) -> SteerMessage: ...
    def get_steer(self, tenant_id: str, owner_id: str, session_id: str, delivery_id: str) -> SteerMessage | None: ...
    def list_written(self, tenant_id: str, owner_id: str, session_id: str) -> list[SteerMessage]: ...
    def reconcile_written(self) -> list[SteerMessage]: ...
    def transition(self, tenant_id: str, owner_id: str, session_id: str, delivery_id: str, state: SteerState, expected_revision: int) -> SteerMessage | None: ...


__all__ = ["SessionStore", "SteerMailbox"]
