"""Scheduler persistence ports."""
from __future__ import annotations

from typing import Protocol

from .models import FireRecord, FireState, ScheduleRecord, ScheduleState


class ScheduleStore(Protocol):
    def create(self, record: ScheduleRecord) -> ScheduleRecord: ...
    def get(self, tenant_id: str, owner_id: str,
            schedule_id: str) -> ScheduleRecord | None: ...
    def list(self, tenant_id: str, owner_id: str) -> list[ScheduleRecord]: ...
    def set_state(self, tenant_id: str, owner_id: str, schedule_id: str,
                  state: ScheduleState, expected_revision: int,
                  next_fire_at: str | None) -> ScheduleRecord | None: ...
    def remove(self, tenant_id: str, owner_id: str, schedule_id: str,
               expected_revision: int) -> bool: ...
    def advance_claim(self, record: ScheduleRecord, fire_sequence: int,
                      next_fire_at: str | None, state: ScheduleState,
                      fired_at: str) -> ScheduleRecord | None: ...
    def create_fire(self, record: FireRecord) -> FireRecord: ...
    def get_fire(self, tenant_id: str, owner_id: str, schedule_id: str,
                 fire_sequence: int) -> FireRecord | None: ...
    def list_due(self, now: str, limit: int = 100) -> list[ScheduleRecord]: ...
    def list_claimed(self, limit: int = 100) -> list[FireRecord]: ...
    def has_nonterminal(self, tenant_id: str, owner_id: str,
                        schedule_id: str) -> bool: ...
    def mark_enrolled(self, fire: FireRecord, workflow_run_id: str,
                      expected_revision: int) -> FireRecord | None: ...

    def list_enrolled(self, limit: int = 100) -> list[FireRecord]: ...
    def mark_outcome(self, fire: FireRecord, state: FireState,
                     expected_revision: int) -> FireRecord | None: ...

__all__ = ["ScheduleStore"]
