"""Port for encrypted protected business-content artifacts."""
from __future__ import annotations
from typing import Any, Protocol
from factory.mcp_utils.interface import AuthorizationAssertion, ProtectedArtifactRef, ProtectedContentDescriptor, ProtectedContentProjection

class BusinessContentArtifactStore(Protocol):
    def create_or_match(self, descriptor: ProtectedContentDescriptor, content: dict[str, Any], assertion: AuthorizationAssertion) -> tuple[str, ProtectedArtifactRef]: ...
    def materialize(self, ref: ProtectedArtifactRef, assertion: AuthorizationAssertion) -> dict[str, Any]: ...
    def project(self, ref: ProtectedArtifactRef, assertion: AuthorizationAssertion) -> ProtectedContentProjection: ...
    def search(self, descriptor: ProtectedContentDescriptor, assertion: AuthorizationAssertion, limit: int = 20) -> list[ProtectedContentProjection]: ...
    def tombstone(self, ref: ProtectedArtifactRef, assertion: AuthorizationAssertion) -> None: ...
    def rekey(self, ref: ProtectedArtifactRef, assertion: AuthorizationAssertion) -> None: ...
