"""Port for durable ML CAN lifecycle attempt and effect storage."""
from __future__ import annotations

from typing import Any, ContextManager, Protocol

from .can_lifecycle_contracts import (
    CanEffectIntent, CanEffectReceipt, CanLifecycleAttempt,
)
from .can_lifecycle_refs import CanConformanceReceiptRef, CanTerminalRef


class CanLifecycleStore(Protocol):
    """Persist and authenticate canonical attempts, terminals, and effects."""

    def lock(self, operation: str, attempt_id: str) -> ContextManager[None]: ...
    def claim(
        self, operation: str, attempt_id: str, request_sha256: str,
    ) -> tuple[str, CanLifecycleAttempt]: ...
    def running(self, record: CanLifecycleAttempt) -> CanLifecycleAttempt: ...
    def publish(self, record: CanLifecycleAttempt, terminal: dict) -> CanLifecycleAttempt: ...
    def load(self, operation: str, attempt_id: str) -> CanLifecycleAttempt | None: ...
    def load_terminal(self, record: CanLifecycleAttempt) -> dict: ...
    def terminal_ref(self, record: CanLifecycleAttempt) -> CanTerminalRef: ...
    def load_terminal_ref(self, value: Any, expected_operation: str) -> dict: ...
    def save_intent(self, intent: CanEffectIntent) -> CanEffectIntent: ...
    def load_intent(self, effect_id: str) -> CanEffectIntent | None: ...
    def load_receipt(self, effect_id: str) -> CanEffectReceipt | None: ...
    def save_receipt(self, receipt: CanEffectReceipt) -> CanEffectReceipt: ...
    def receipt_ref(
        self, effect_id: str, expected_operation: str,
    ) -> CanConformanceReceiptRef: ...
    def load_conformance_receipt(
        self, value: Any, expected_operation: str,
    ) -> tuple[CanEffectIntent, CanEffectReceipt]: ...


__all__ = ["CanLifecycleStore"]
