"""Dockerfile templates for blueprint deployment artifacts."""

from __future__ import annotations

from .introspect import ProjectInfo, BASE_PROCESS_MAP


def render_dockerfile(info: ProjectInfo, target: str = "docker") -> str:
    """Render a Dockerfile for the project."""
    if target == "lambda":
        return _render_lambda(info)
    return _render_standard(info)


def _render_standard(info: ProjectInfo) -> str:
    default_cmd = "python"
    for base in info.bases:
        if base in info.scripts.values() or base in BASE_PROCESS_MAP:
            break
    if info.scripts:
        default_cmd = list(info.scripts.keys())[0]

    return f"""\
# Auto-generated by blueprint for project: {info.name}
# Targets: {', '.join(info.bases)} bases, {len(info.components)} components

FROM python:{info.python_version}-slim AS builder
COPY --from=ghcr.io/astral-sh/uv:latest /uv /bin/uv
WORKDIR /build
COPY pyproject.toml workspace.toml uv.lock ./
COPY src/ src/
COPY components/ components/
COPY bases/ bases/
COPY projects/{info.name}/ projects/{info.name}/
RUN uv build --package {info.name} --wheel --out-dir /dist

FROM python:{info.python_version}-slim AS runtime
COPY --from=ghcr.io/astral-sh/uv:latest /uv /bin/uv
WORKDIR /app
COPY --from=builder /dist/*.whl /tmp/
RUN uv pip install --system /tmp/*.whl && rm -rf /tmp/*.whl
COPY BRICKS_INDEX.yaml .
CMD ["{default_cmd}"]
"""


def _render_lambda(info: ProjectInfo) -> str:
    return f"""\
# Auto-generated by blueprint for project: {info.name} (Lambda target)

FROM public.ecr.aws/lambda/python:{info.python_version} AS builder
COPY --from=ghcr.io/astral-sh/uv:latest /uv /bin/uv
WORKDIR /build
COPY pyproject.toml workspace.toml uv.lock ./
COPY src/ src/
COPY components/ components/
COPY bases/ bases/
COPY projects/{info.name}/ projects/{info.name}/
RUN uv build --package {info.name} --wheel --out-dir /dist

FROM public.ecr.aws/lambda/python:{info.python_version}
COPY --from=builder /dist/*.whl /tmp/
RUN pip install /tmp/*.whl && rm -rf /tmp/*.whl
COPY BRICKS_INDEX.yaml ${{LAMBDA_TASK_ROOT}}/
CMD ["factory.api.main.handler"]
"""
