"""Deployment artifact templates.

Generates docker-compose services, Makefile, and .env
from a ProjectInfo brick graph.  Dockerfile rendering
lives in dockerfiles.py (SRP split for <200 LOC).
"""

from __future__ import annotations

from .dockerfiles import render_dockerfile  # noqa: F401 — re-export
from .introspect import ProjectInfo, BASE_PROCESS_MAP

# ── Infra service defaults (for .env generation) ──────────────────────
INFRA_ENV_VARS: dict[str, list[tuple[str, str, str]]] = {
    "postgres": [
        ("FACTORY_POSTGRES_URL", "postgresql://factory:factory@postgres:5432/factory", "Meta DB"),
    ],
    "neo4j": [
        ("FACTORY_NEO4J_URL", "bolt://neo4j:7687", "Graph DB"),
        ("FACTORY_NEO4J_USER", "neo4j", ""),
        ("FACTORY_NEO4J_PASSWORD", "password", ""),
    ],
    "redis": [
        ("FACTORY_REDIS_URL", "redis://redis:6379/0", "Cache / Broker"),
        ("FACTORY_CELERY_BROKER_URL", "redis://redis:6379/1", "Celery broker"),
    ],
    "keycloak": [
        ("FACTORY_KEYCLOAK_URL", "http://keycloak:8080", "Auth / IAM"),
        ("FACTORY_KEYCLOAK_REALM", "factory", ""),
        ("FACTORY_KEYCLOAK_CLIENT_ID", "factory-mcp", ""),
    ],
    "seaweedfs": [
        ("FACTORY_SEAWEED_URL", "http://seaweedfs:9333", "Object Storage"),
    ],
    "chromadb": [
        ("FACTORY_CHROMA_HOST", "chromadb", "Vector DB"),
        ("FACTORY_CHROMA_PORT", "8000", ""),
    ],
    "phoenix": [
        ("FACTORY_PHOENIX_URL", "http://phoenix:6006", "LLM Telemetry"),
    ],
}


def render_compose_services(info: ProjectInfo) -> str:
    """Render docker-compose service entries for the project."""
    lines = [f"  # === {info.name} Application Services ===", ""]

    for script_name, entry_point in info.scripts.items():
        svc_name = f"{info.name}-{script_name.split('-')[-1]}"
        port_line = ""

        # Detect port from base type
        for base, meta in BASE_PROCESS_MAP.items():
            if f"factory.{base}" in entry_point and meta["port"]:
                host_port = int(meta["port"]) + 100  # offset to avoid conflicts
                port_line = f"\n    ports:\n      - \"{host_port}:{meta['port']}\""
                break

        depends = ", ".join(info.infra_services[:3]) if info.infra_services else "redis"
        lines.append(f"  {svc_name}:")
        lines.append(f"    build:")
        lines.append(f"      context: .")
        lines.append(f"      dockerfile: projects/{info.name}/Dockerfile")
        lines.append(f"    command: [\"{script_name}\"]")
        lines.append(f"    env_file: projects/{info.name}/.env")
        if port_line:
            lines.append(port_line.rstrip())
        lines.append(f"    depends_on:")
        for svc in info.infra_services[:5]:
            lines.append(f"      - {svc}")
        lines.append("")

    return "\n".join(lines)


def render_makefile(info: ProjectInfo) -> str:
    """Render a Makefile for the project."""
    svc_names = " ".join(
        f"{info.name}-{s.split('-')[-1]}" for s in info.scripts
    )
    infra = " ".join(info.infra_services)

    return f"""\
# Auto-generated by blueprint for project: {info.name}
.PHONY: help dev stop build up test check

PROJECT = {info.name}

help:
\t@echo "{info.name} commands:"
\t@echo "  make dev   - Start infrastructure services"
\t@echo "  make stop  - Stop all services"
\t@echo "  make build - Build Docker images"
\t@echo "  make up    - Start full stack"
\t@echo "  make test  - Run tests"
\t@echo "  make check - Run guardian compliance check"

dev:
\tdocker compose up -d {infra}

stop:
\tdocker compose down

build:
\tdocker compose build {svc_names}

up: dev
\tdocker compose up -d {svc_names}

test:
\tuv run pytest

check:
\tuv run python -c "from factory.foreman.interface import guardian_check; print(guardian_check())"
"""


def render_env_example(info: ProjectInfo) -> str:
    """Render .env.example from project's infra dependencies."""
    lines = [f"# {info.name} — environment configuration", ""]

    # Adapter selections
    if info.adapter_selections:
        lines.append("# === Adapter Selections ===")
        lines.append("# Change these to control which Docker services are needed")
        for brick in sorted(info.adapter_selections):
            if brick in info.components:
                val = info.adapter_selections[brick]
                lines.append(f"FACTORY_{brick.upper()}_ADAPTER={val}")
        lines.append("")

    # Infra service env vars (only for services actually selected)
    for svc in info.infra_services:
        env_vars = INFRA_ENV_VARS.get(svc, [])
        if env_vars:
            lines.append(f"# === {svc.title()} ===")
            for var_name, default, comment in env_vars:
                suffix = f"  # {comment}" if comment else ""
                lines.append(f"{var_name}={default}{suffix}")
            lines.append("")

    # Add base-specific env vars
    if "api" in info.bases:
        lines.extend(["# === API Base ===", "FACTORY_API_HOST=0.0.0.0", "FACTORY_API_PORT=8000", ""])
    if "worker" in info.bases:
        lines.extend(["# === Worker Base ===", "FACTORY_WORKER_BACKEND=celery", ""])

    return "\n".join(lines)
