/**
 * Schema-to-form derivation, proved against REAL shipped schemas (bd:3jcls.4).
 *
 * Anti-drift condition 4: no hand-written fixture. `fixtures/real-tool-schemas.json`
 * is generated by `scripts/dump_real_tool_schemas.py` straight out of the live
 * aggregator, and `test_catalog_fixture_matches_live_schemas.py` fails if a
 * brick's signature moves without regenerating it. So these assertions are
 * about `cache_set` / `cache_keys` / `cache_stats` / `telemetry_record_log`
 * exactly as they exist today, not about a shape someone imagined.
 */

import { describe, expect, it } from "vitest";
import fixture from "./fixtures/real-tool-schemas.json";
import {
  coerceValues, deriveFields, initialValues, missingRequired,
} from "@/lib/schema-form";
import type { CatalogTool } from "@/lib/tool-catalog";

const TOOLS = fixture.tools as unknown as CatalogTool[];

function tool(name: string): CatalogTool {
  const found = TOOLS.find((t) => t.qualified_name === name);
  if (!found) throw new Error(`fixture missing ${name}`);
  return found;
}

function field(name: string, toolName: string) {
  const found = deriveFields(tool(toolName).input_schema).find((f) => f.name === name);
  if (!found) throw new Error(`${toolName} has no param ${name}`);
  return found;
}

describe("deriveFields against real brick schemas", () => {
  it("marks schema-required params required (cache_set)", () => {
    const fields = deriveFields(tool("cache_set").input_schema);
    expect(fields.map((f) => f.name)).toEqual(["key", "value", "ttl_seconds"]);
    expect(field("key", "cache_set").required).toBe(true);
    expect(field("value", "cache_set").required).toBe(true);
    expect(field("ttl_seconds", "cache_set").required).toBe(false);
  });

  it("unwraps `int | None = None` into a numeric field (cache_set.ttl_seconds)", () => {
    // Ships as {anyOf: [{integer}, {null}], default: null} with NO top-level
    // `type` — without unwrapping this would render as a raw JSON box.
    const ttl = field("ttl_seconds", "cache_set");
    expect(ttl.kind).toBe("integer");
    expect(ttl.nullable).toBe(true);
    expect(ttl.defaultValue).toBeNull();
  });

  it("renders a Literal as an enum with its real options (telemetry_record_log)", () => {
    const severity = field("severity", "telemetry_record_log");
    expect(severity.kind).toBe("enum");
    expect(severity.required).toBe(true);
    expect(severity.options).toContain("INFO");
    expect(severity.options).toContain("ERROR");
  });

  it("unwraps a nullable object into the JSON branch (telemetry attributes)", () => {
    const attributes = field("attributes", "telemetry_record_log");
    expect(attributes.kind).toBe("json");
    expect(attributes.nullable).toBe(true);
  });

  it("carries a real string default (cache_keys.pattern = '*')", () => {
    const pattern = field("pattern", "cache_keys");
    expect(pattern.kind).toBe("string");
    expect(pattern.required).toBe(false);
    expect(pattern.defaultValue).toBe("*");
  });

  it("yields no fields for a zero-argument tool (cache_stats)", () => {
    expect(deriveFields(tool("cache_stats").input_schema)).toEqual([]);
  });
});

describe("initialValues prefills schema defaults", () => {
  it("prefills cache_keys.pattern from the schema", () => {
    const fields = deriveFields(tool("cache_keys").input_schema);
    expect(initialValues(fields)).toEqual({ pattern: "*" });
  });

  it("leaves null-defaulted params blank and preselects the first enum", () => {
    expect(initialValues(deriveFields(tool("cache_set").input_schema)).ttl_seconds).toBe("");
    const severity = initialValues(
      deriveFields(tool("telemetry_record_log").input_schema),
    ).severity;
    expect(field("severity", "telemetry_record_log").options[0]).toBe(severity);
  });
});

describe("missingRequired gates submit", () => {
  it("reports every unfilled required param, and none when filled", () => {
    const fields = deriveFields(tool("cache_set").input_schema);
    expect(missingRequired(fields, initialValues(fields))).toEqual(["key", "value"]);
    expect(
      missingRequired(fields, { key: "k", value: "v", ttl_seconds: "" }),
    ).toEqual([]);
    expect(missingRequired(fields, { key: "  ", value: "v" })).toEqual(["key"]);
  });
});

describe("coerceValues builds the wire args", () => {
  it("coerces a real integer param and omits blank optionals", () => {
    const fields = deriveFields(tool("cache_set").input_schema);
    expect(coerceValues(fields, { key: "k", value: "v", ttl_seconds: "" })).toEqual({
      key: "k", value: "v",
    });
    expect(coerceValues(fields, { key: "k", value: "v", ttl_seconds: "30" })).toEqual({
      key: "k", value: "v", ttl_seconds: 30,
    });
  });

  it("parses a JSON param and keeps enum values as strings", () => {
    const fields = deriveFields(tool("telemetry_record_log").input_schema);
    expect(
      coerceValues(fields, {
        severity: "INFO", body: "hello", attributes: '{"a":1}',
      }),
    ).toEqual({ severity: "INFO", body: "hello", attributes: { a: 1 } });
  });

  it("sends nothing for a zero-argument tool", () => {
    expect(coerceValues(deriveFields(tool("cache_stats").input_schema), {})).toEqual({});
  });
});
