"""Devtools runtime port."""
from __future__ import annotations

from typing import Protocol

from .models import (
    CommandResult, DirectoryListing, FileRead, FileWrite, GitResult,
    ProjectBinding, SearchResult,
)


class DevtoolsPort(Protocol):
    def read_file(self, binding: ProjectBinding, path: str,
                  offset: int = 0, limit: int = 2000) -> FileRead: ...
    def list_dir(self, binding: ProjectBinding, path: str,
                 limit: int = 500) -> DirectoryListing: ...
    def create_file(self, binding: ProjectBinding, path: str,
                    content: str) -> FileWrite: ...
    def edit_file(self, binding: ProjectBinding, path: str, content: str,
                  base_sha256: str) -> FileWrite: ...
    def run_command(self, binding: ProjectBinding, argv: list[str], cwd: str = ".", *,
                    timeout_seconds: float = 60.0,
                    output_limit: int = 65_536) -> CommandResult: ...
    def cancel_command(self, binding: ProjectBinding, run_id: str) -> bool: ...
    def git_status(self, binding: ProjectBinding) -> GitResult: ...
    def git_diff(self, binding: ProjectBinding, paths: list[str], *,
                 staged: bool = False) -> GitResult: ...
    def git_log(self, binding: ProjectBinding, paths: list[str] | None = None, *,
                limit: int = 20) -> GitResult: ...
    def git_stage(self, binding: ProjectBinding, paths: list[str]) -> GitResult: ...
    def git_commit(self, binding: ProjectBinding, message: str, *,
                   skip_hooks: bool = False) -> GitResult: ...
    def git_push(self, binding: ProjectBinding, remote: str, branch: str, *,
                 set_upstream: bool = False) -> GitResult: ...
    def search(self, binding: ProjectBinding, query: str,
               path: str, glob: str | None,
               limit: int = 100) -> SearchResult: ...


__all__ = ["DevtoolsPort"]
